let router 			= require('express').Router()
let req	 			= require('./req')
let chat 			= require('./chat')
let test 			= require('./test')
let graph 			= require('./graph')
let group 			= require('./group')
let chart 			= require('./schedule')
let level 			= require('./level')
let notice 			= require('./notice')
let result 			= require('./result')
let account 		= require('./account')
let student 		= require('./student')
let teacher 		= require('./teacher')
let sendFile 		= require('./sendFile')
let template 		= require('./template')
let uploadPicture 	= require('./uploadPicture')
	
router.post('/req', req)
router.post('/chat', chat)
router.post('/test', test)
router.post('/chart', chart)
router.post('/graph', graph)
router.post('/group', group)
router.post('/level', level)
router.post('/notice', notice)
router.post('/result', result)
router.post('/account', account)
router.post('/student', student)
router.post('/teacher', teacher)
router.post('/sendFile', sendFile)
router.post('/template', template)
router.post('/uploadPicture', uploadPicture)

module.exports = router